# Generated by Django 4.0.4 on 2022-05-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msafiri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='title',
        ),
    ]
