# Generated by Django 4.0.4 on 2022-05-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msafiri', '0002_rename_img_name_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='msafiri.category'),
        ),
    ]
