# Generated by Django 4.0.4 on 2022-05-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msafiri', '0003_remove_image_category_image_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
